export const POLICY_SMART_WALLET_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", type: "address" },
      { name: "_trustedSigner", type: "address" },
      { name: "_guardian", type: "address" },
      { name: "_delayDuration", type: "uint256" },
    ],
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "execute",
    inputs: [
      {
        name: "op",
        type: "tuple",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
          { name: "nonce", type: "uint256" },
          { name: "decision", type: "uint8" },
          { name: "expiry", type: "uint256" },
        ],
      },
      { name: "ownerSig", type: "bytes" },
      { name: "attestationSig", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeWithGuardian",
    inputs: [
      {
        name: "op",
        type: "tuple",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
          { name: "nonce", type: "uint256" },
          { name: "decision", type: "uint8" },
          { name: "expiry", type: "uint256" },
        ],
      },
      { name: "ownerSig", type: "bytes" },
      { name: "guardianSig", type: "bytes" },
      { name: "attestationSig", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeQueued",
    inputs: [
      {
        name: "op",
        type: "tuple",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
          { name: "nonce", type: "uint256" },
          { name: "decision", type: "uint8" },
          { name: "expiry", type: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelQueued",
    inputs: [{ name: "opHash", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nonce",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "trustedSigner",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "delayDuration",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isGuardian",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGuardians",
    inputs: [],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQueuedOpHashes",
    inputs: [],
    outputs: [{ type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQueuedOperation",
    inputs: [{ name: "opHash", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "opHash", type: "bytes32" },
          { name: "executeAfter", type: "uint256" },
          { name: "executed", type: "bool" },
          { name: "cancelled", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashOperation",
    inputs: [
      {
        name: "op",
        type: "tuple",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
          { name: "nonce", type: "uint256" },
          { name: "decision", type: "uint8" },
          { name: "expiry", type: "uint256" },
        ],
      },
    ],
    outputs: [{ type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Executed",
    inputs: [
      { name: "opHash", type: "bytes32", indexed: true },
      { name: "target", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OperationQueued",
    inputs: [
      { name: "opHash", type: "bytes32", indexed: true },
      { name: "executeAfter", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OperationCancelled",
    inputs: [{ name: "opHash", type: "bytes32", indexed: true }],
  },
  {
    type: "event",
    name: "OperationExecutedFromQueue",
    inputs: [{ name: "opHash", type: "bytes32", indexed: true }],
  },
] as const;
